### PR TITLE
I UPDATED YOUR FUCKING BOT

### PR DESCRIPTION
**Pull request by bdotsamir**
god i kept on telling you to do it but NOOOOOOO IT'S TOO MUCH WORK
So, now that I host your bot, I did it for you.

:angery:

### CODE REVIEW

**Comment by ProbablyGallium** [comment]
tbh I don't intend to maintain this repo make the bot closed source from here on out. I'll probably delete this repo too. Sorry.

**Comment by bdotsamir** [comment]
hey now why is that? why do you wanna make it closed source?

**Comment by ProbablyGallium** [comment]
because tbh the bot is pretty much dead at this point and in addition, maintaining this repo has led to multiple commits of my bot token, one of which lead to the bot leaving every server, and I don't want to take any more chances.

**Comment by matthewzring** [comment]
Why don't you just `.gitignore` your config file

**Comment by bdotsamir** [comment]
I did that.. and he closed the pr
#13 
@ringmatthew

**Pull request closed without merging**
